### ISSUE TITLE
recover multiple specs from files

### ISSUE THREAD

**Issue by thomased** [rmaia/pavo#156]
It'd probably be a pain, but I wonder if `getspec()` could handle retrieving multiple spectra stored in a single file`('wl' | 'spec1' | 'spec2' | ...)`, which is pretty common. I was slightly thrown when trying to import a bunch of `.txt`'s containing multiple specs, because `getspec()` silently returns only the first spec. I wonder if that should (a) not be so silent, or (b) just be able to handle it?

**Comment by Bisaloo** [comment]
I don't think it would be a good idea to go down that road. Many spectrometers do not only export `| wl | spec |` but instead `| wl | count | whiteref | darkref | processed |`. I don't see any good way for `getspec()` to detect whether we're in this case or in the case you're describing.

We could however offer more guidance to users that have spectra stored in a single file, namely tell them that they can do `as.rspec(read.table(file))`.

A warning might help but it may be tricky because of the reason I mentioned above.

**Comment by thomased** [comment]
Yeah, of course, fair point. The quietness of it bothered me, but not sure there's much to be done.

**Comment by GloverLab** [comment]
For anyone coming back to this, if it's in any way useful: the current OceanArt software will save several spectra in one file, which aren't imported properly into Pavo (which only imports the first one). Here's an R script to split them out: it leaves the first eight columns, then takes pairs of columns from 9:10 thru the width of the data frame Works for me, may not work for you, test everything, supplied with no warranty, etc. etc. etc.

`# Install the required package
install.packages("readr")
install.packages("stringr")
# Load the installed Package
library(readr)
library(stringr)

#Replace this path with the path to your file
#Also, inspect your file . It should have columns Spectrometer, Serial Number, Number of Pixels, Save Format, Type, Wavelengths,  Wave Numbers, Reference, Dark, and then Sample and Reflectance for all your samples. You may have more Reference and Dark ones in there because of extra readings (it seems that even if you delete readings they remain in the session?). Take care!
#Individual files will be generated in this folder as well. 
setwd("/Users/Hamish/Desktop/specs")
data <- read_tsv("10x3Y10x3P.tsv")
for(i in seq(from=10, to=ncol(data), by=2)){
  write_tsv(data[c(1:8,i-1:i)],path=paste("spectrum-",str_pad(i,4,pad="0"),".tsv",sep=""))
}
`

Bisaloo - not expecting any fixes in Pavo, just pasting this here to give an example for others of how to split a single file into multiple.
