### ISSUE TITLE
better way to show color space documentations

### ISSUE THREAD

**Issue by rmaia** [rmaia/pavo#31]
since in the new version of pavo all color spaces will be wrapped in the colspace function and internally hidden, we need a better way of letting users access the manuals for these different color spaces. Maybe links in the main function?

(ping @thomased @celiason @bittonp)

**Comment by thomased** [comment]
Yeah, tricky. I like the idea of a brief summary in the top level functions (colspace, plot.colspace etc.) with links. An issue being that we'd have to export all the individual functions to access their documentation (I think?), which seems messy since users don't really need access to them.

Ah, after some poking around, one option is to @export all the individual functions (dispace, trispace etc.) but mark them '@keywords internal'. That allows access/links to their documentation but hides them in the main index. I think we'd need to lose the leading period for internal function names too - links don't seem to work otherwise. 

I'm a bit of a rookie with this stuff, could be an easier way...

**Comment by rmaia** [comment]
I didn't know about the keyword trick, that might do it. Another option is to build the help functions like the  data help files and export them independently? Anyway I think your idea is better.

**Comment by thomased** [comment]
Roughed in - 49d72c3. Take a look at ?colspace to see if you like the idea. It has the added benefit of letting advanced users poke around the individual model functions/calculations pretty easily, which is nice. I still need to go through and tighten up the new documentation a bit.

**Comment by thomased** [comment]
Now done the same for plot.colspace in 3570406 . Looks like a reasonable approach, just reopen if not....
