### ISSUE TITLE
Ocular media transmission in vismodel and sensmodel give different results

### ISSUE THREAD

**Issue by bittonp** [rmaia/pavo#49]
Having om in sensmodel and trans in vismodel could cause problems. If misunderstood and used twice, this has obvious consequences.
A bigger problem is that applying om or trans gives different results when integrate = T in sensmodel (the results are the same when integrate = F).

**Comment by rmaia** [comment]
A couple things:

* possible solution: add attribute to sensmodel output that gets checked in vismodel, with warning if double ocular transmission happens.

* also we need to clarify what the "bird" option means, since there is variation between species.

* finally, I think the ocular media effect has to come AFTER integration, not before. Possibly related to https://github.com/rmaia/pavo/issues/49

**Comment by rmaia** [comment]
first stab at it: https://github.com/rmaia/pavo/commit/d98940231abbcec7bfa2a81ff8b14084482022df
