### ISSUE TITLE
tetraplot creates a strange white rectangle

### ISSUE THREAD

**Issue by Bisaloo** [rmaia/pavo#88]
Example:

```r
library(pavo)

data(flowers)

vis_flowers <- vismodel(flowers)
tcs_flowers <- colspace(vis_flowers)

plot(tcs_flowers)
```
I updated the plot background with Inkscape to highlight what I'm talking about.

![rplot pdf](https://user-images.githubusercontent.com/10783929/38488301-589ec288-3be3-11e8-92a6-13b0a97baddb.png)

I noticed this when preparing slides with a non-white background.

My gut feeling is that it has something to do with plot initialization but I would need to dig deeper in the code to make sure. I can't do this right now but I will have a look whenever I get some time.

**Comment by thomased** [comment]
Hah - bizarre. Nice catch @Bisaloo, will have a look.

**Comment by rmaia** [comment]
yeah I had noticed before and I thought I had patched it, but I guess the issue might have returned when I redid the plotting code. You're right, it has to do with the initialization of the plot space, defining the axis ranges. 3D plots are definitely not R's forte and we've been struggling with getting this plot to work without a hitch since day 1...

**Comment by rmaia** [comment]
The plane drawn is unavoidable when using `persp`, which has been the best option for 3D-to-2D transformation. Unfortunately the best way to deal with this, I think, would be to fork and modify that function...
