### ISSUE TITLE
Tetraplot does not work for single spectrum

### ISSUE THREAD

**Issue by Bisaloo** [rmaia/pavo#97]
Reprex:

``` r
library(pavo)
data(sicalis)
vis_sicalis = vismodel(sicalis)
tcs_sicalis = colspace(vis_sicalis)
plot(tcs_sicalis)
```

![](https://i.imgur.com/U7AO6BV.png)

``` r
sicalis1 = sicalis[,c(1:2)]
vis_sicalis1 = vismodel(sicalis1)
tcs_sicalis1 = colspace(vis_sicalis1)
plot(tcs_sicalis1)
```

![](https://i.imgur.com/Yhix8Ip.png)

``` r
sicalis2 = sicalis[,c(1:3)]
vis_sicalis2 = vismodel(sicalis2)
tcs_sicalis2 = colspace(vis_sicalis2)
plot(tcs_sicalis2)
```

![](https://i.imgur.com/IK6F2tI.png)

I will try to have a look whenever I get a moment.

**Comment by thomased** [comment]
Baffling. The single-spectrum data _seem_ to make it down to the `do.call(points, argpoints)` (line 356-357) call fine & as expected (from what I can tell they're meant to look like), but they aren't plotted.

Interestingly single specs are plotted fine when `type = 'l'`, so the problem is down that way I think.
